import Head from "next/head";
import { useState } from "react";
import styles from "@/styles/Home.module.css";

import { useEvmWalletNFTs } from "@moralisweb3/next";
import { EvmNftish } from "@moralisweb3/common-evm-utils";
import {
  Grid,
  GridItem,
  Box,
  Center,
  Modal,
  ModalOverlay,
  ModalContent,
  ModalHeader,
  ModalFooter,
  ModalBody,
  ModalCloseButton,
  Button,
  useDisclosure,
  Text,
} from "@chakra-ui/react";

interface MetaData {
  name: string;
  description: string;
  image: string;
}

function HomePage() {
  const address = "0xd8da6bf26964af9d7eed9e03e53415d37aa96045";
  const { data: nativeNFTs } = useEvmWalletNFTs({ address });
  const { isOpen, onOpen, onClose } = useDisclosure();
  const [nftData, setNftData] = useState<EvmNftish>({} as EvmNftish);
  const handleClick = (nft: EvmNftish) => {
    setNftData(nft);
    onOpen();
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box m="20px" className={styles.main}>
        <Grid templateColumns="repeat(5, 1fr)" gap={6}>
          {nativeNFTs &&
            nativeNFTs.map((nft, index) => (
              <GridItem
                onClick={() => {
                  handleClick(nft);
                }}
                key={index}
                colSpan={1}
                w="100%"
                h="80px"
                bg="gray.200"
                color="black"
                _hover={{ bg: "gray.500", cursor: "pointer" }}
                borderRadius={5}
                alignItems="center"
                justifyContent="center"
                display="flex"
                flexDir="column"
              >
                <Center textAlign="center">{nft.name}</Center>
              </GridItem>
            ))}
        </Grid>
        <Modal isOpen={isOpen} onClose={onClose}>
          <ModalOverlay />
          <ModalContent bg="white" color="black">
            <ModalHeader>
              <Text textStyle="bold">{nftData.name}</Text>
            </ModalHeader>
            <ModalCloseButton />
            <ModalBody>
              <Text>
                <b>Contract_Type: </b> {nftData.contractType as string}
              </Text>
              <Text>
                <b>Description: </b>
                {((nftData.metadata as unknown as MetaData)?.description ??
                  "") !== ""
                  ? (nftData.metadata as unknown as MetaData)?.description
                  : "No descriptioin"}
              </Text>
            </ModalBody>

            <ModalFooter>
              <Button
                bgColor="gray.900"
                color="white"
                _hover={{ bg: "green.300" }}
                mr={3}
                onClick={() => {
                  document.location = `https://opensea.io/assets/ethereum/${
                    JSON.parse(JSON.stringify(nftData.tokenAddress))._value
                  }/${nftData.tokenId}`;
                }}
              >
                Go to OpenSea
              </Button>
            </ModalFooter>
          </ModalContent>
        </Modal>
      </Box>
    </>
  );
}

export default HomePage;
